import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Section } from "@/components/Sections";
import { bloxline } from "@/lib/publications";

export const metadata:Metadata={title:"About The Redditrepreneur",description:"The Redditrepreneur is a Community Intelligence research and publishing company founded by Tonte Bo Douglas."};

export default function Page(){return <><header className="page-hero"><div className="shell"><p className="eyebrow">About The Redditrepreneur</p><h1>Researching what online communities really think.</h1><p className="lede">The Redditrepreneur is a Community Intelligence research and publishing company founded by Tonte Bo Douglas.</p></div></header><Section title="What we do"><div className="split"><div className="prose"><p>We study what online communities say about brands, industries, products and culture.</p><p>Our research helps businesses understand trust, reputation, customer behaviour, emerging risks and market opportunities.</p><p>We publish research across industries and build specialist publications that help audiences understand important online communities.</p><h3>Applying the research</h3><p>Businesses can apply our methodology through audits, workshops, advisory work and Community Intelligence software.</p><div className="button-row"><a className="button" href="https://blog.theredditrepreneur.com">Explore the research</a><Link className="button secondary" href="/services">Work with us</Link></div></div><Image className="founder" src="/founder/tonte-bo-douglas.jpg" alt="Tonte Bo Douglas, founder of The Redditrepreneur" width={400} height={400}/></div></Section><Section eyebrow="Our publishing ecosystem" title="Building specialist publications" className="alt"><div className="prose"><p>Alongside our wider Community Intelligence research, The Redditrepreneur creates specialist publications focused on individual ecosystems.</p><p>Our first is <a className="text-link" href={bloxline.url} target="_blank" rel="noopener noreferrer">The Bloxline</a>, The Adult’s Guide to Roblox.</p><p>It helps adults understand one of the world’s most influential gaming and creator platforms through clear reporting, education and industry analysis.</p><div className="button-row"><Link className="button secondary" href="/publications">Explore our publications</Link></div></div></Section></>}
