import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { PublicationCard } from "@/components/PublicationCard";
import { Section } from "@/components/Sections";
import { publications } from "@/lib/publications";

export const metadata:Metadata={title:"About The Redditrepreneur",description:"The Redditrepreneur builds specialist intelligence brands around emerging digital communities, connected by Community Intelligence.",alternates:{canonical:"/about"}};

export default function Page(){return <><header className="page-hero"><div className="shell"><p className="eyebrow">About The Redditrepreneur</p><h1>We build intelligence brands around emerging digital communities.</h1><p className="lede">We believe some of tomorrow’s most important industries begin as online communities.</p></div></header><Section title="We go where communities become industries."><div className="narrow-copy"><p>The Redditrepreneur identifies emerging communities early, studies how they develop and creates specialist intelligence brands around them.</p><p>Each brand combines editorial, community, industry and commercial intelligence to make a complex ecosystem easier to understand.</p><p>Community Intelligence is the methodology connecting the portfolio.</p></div></Section><Section eyebrow="Current portfolio" title="Our intelligence brands" className="alt"><div className="intelligence-brand-grid">{publications.map(publication=><PublicationCard key={publication.slug} publication={publication}/>)}</div></Section><Section eyebrow="Founder" title="Built from direct community experience"><div className="founder-compact"><Image className="founder" src="/founder/tonte-bo-douglas.jpg" alt="Tonte Bo Douglas, founder of The Redditrepreneur" width={400} height={400}/><div className="prose"><p>The Redditrepreneur was founded by Tonte Bo Douglas. His experience includes working directly at Reddit and building Reddit and community presences for Greggs, Expedia, Vrbo and Hotels.com.</p><p>That experience inside online communities provides the practical foundation for how The Redditrepreneur researches ecosystems and develops its intelligence brands.</p><div className="button-row"><Link className="button" href="/contact">Start a conversation</Link></div></div></div></Section></>}
