import type { Metadata } from "next";
import Link from "next/link";
import { PublicationCard } from "@/components/PublicationCard";
import { Section } from "@/components/Sections";
import { publications } from "@/lib/publications";
import { site } from "@/lib/site";

export const metadata:Metadata={title:"Intelligence Brands",description:"Explore The Redditrepreneur’s intelligence brands for emerging digital communities, including The Bloxline and The CHNNL.",alternates:{canonical:"/publications"},openGraph:{title:"Intelligence Brands from The Redditrepreneur",description:"Specialist intelligence brands for communities becoming meaningful industries.",url:"/publications",images:[{url:"/brand/redditrepreneur-logo.png",width:1024,height:1024,alt:"The Redditrepreneur"}]}};

export default function PublicationsPage(){const canonical=`${site.url}/publications`;const schema={"@context":"https://schema.org","@graph":[{"@type":"CollectionPage","@id":canonical,name:"Intelligence brands from The Redditrepreneur",url:canonical,description:"A portfolio of specialist intelligence brands for emerging digital communities.",hasPart:publications.map(publication=>({"@type":"WebSite",name:publication.name,description:publication.description,url:publication.url,publisher:{"@id":`${site.url}/#organisation`}}))},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:site.url},{"@type":"ListItem",position:2,name:"Intelligence brands",item:canonical}]}]};return <><header className="page-hero"><div className="shell"><p className="eyebrow">Our portfolio</p><h1>Intelligence brands for emerging digital communities.</h1><p className="lede">The Redditrepreneur builds focused intelligence brands where communities are creating new industries, behaviours and business opportunities.</p></div></header><Section title="Our intelligence brands"><div className="intelligence-brand-grid">{publications.map(publication=><PublicationCard key={publication.slug} publication={publication}/>)}</div><article className="future-brand"><p className="eyebrow">What comes next</p><h3>More communities are coming.</h3><p>Our portfolio is designed to grow as new digital communities develop their own economies, careers, technologies and cultures.</p></article></Section><Section eyebrow="The portfolio thesis" title="We go where communities become industries." className="alt"><div className="narrow-copy"><p>We identify emerging ecosystems early, study the people and organisations shaping them and create dedicated intelligence brands that make them easier to understand.</p><p>Community Intelligence connects the portfolio by turning public conversations, behaviours, beliefs and emerging signals into useful insight.</p></div><div className="button-row"><Link className="button secondary" href="/community-intelligence">Learn about Community Intelligence</Link></div></Section><Section title="Work with an intelligence brand" intro="We work with organisations that want to understand, enter or grow within the communities our brands cover." className="dark"><div className="button-row"><Link className="button" href="/contact">Start a conversation</Link></div></Section><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/></>}
