import Image from "next/image"; import Link from "next/link"; import { Cards, ProductCard, Section } from "@/components/Sections"; import { primaryCta, products, services, site, solutions } from "@/lib/site";
const research=[
 {title:"The Death of Social Listening",description:"Why brands need context, trust and consensus—not just mention counts.",href:"https://blog.theredditrepreneur.com/the-death-of-social-listening-why-brands-are-switching-to-community-intelligence/"},
 {title:"2026 B2B SaaS Benchmarks",description:"Tracking Share of Consensus across B2B SaaS community conversations.",href:"https://blog.theredditrepreneur.com/the-2026-b2b-saas-community-intelligence-benchmarks-tracking-share-of-consensus/"},
 {title:"Community Intelligence Index #1",description:"The state of online communities and the signals shaping markets.",href:"https://blog.theredditrepreneur.com/community-intelligence-index-1-the-state-of-online-communities-june-2026/"},
 {title:"Gymshark Scorecard",description:"A practical Community Intelligence Scorecard applied to Gymshark.",href:"https://blog.theredditrepreneur.com/the-redditrepreneur-community-intelligence-scorecard-gymshark/"},
 {title:"Streamer University",description:"What a creator-led institution reveals about Community Intelligence.",href:"https://blog.theredditrepreneur.com/what-streamer-university-teaches-us-about-community-intelligence/"},
 {title:"GTA 6",description:"The weight of expectation across millions of online conversations.",href:"https://blog.theredditrepreneur.com/gta-6-the-weight-of-expectation/"},
];
const frameworks=["Community Gravity","Expectation Gravity","Trust Collapse","Narrative Compression","Belief Correction","Mission Premium","Hype Hangover","Market Gravity","Community Intelligence Stack","Share of Consensus"].map(title=>({title,description:"Explore the approved definition, related concepts and applications in The Redditrepreneur Knowledge Base.",href:site.researchUrl}));
export default function Home(){return <>
 <section className="hero"><div className="shell hero-grid"><div><p className="eyebrow">The Home of Community Intelligence</p><h1>Understand What Online Communities Really Think.</h1><p className="lede">Turn real conversations into customer insight, competitor intelligence and better business decisions.</p><div className="button-row"><a className="button" href={primaryCta.href}>Explore the Community Intelligence Platform</a><Link className="button secondary" href="/community-intelligence">What Is Community Intelligence?</Link></div></div><div className="hero-visual"><Image src="/platform/dashboard.jpg" alt="The Redditrepreneur Community Intelligence Platform dashboard" width={1920} height={1080} priority/></div></div></section>
 <Section eyebrow="One connected company" title="Community Intelligence, Built Into a Complete Ecosystem" intro="Software, original research, practical frameworks, professional services and products—designed to turn community conversations into clearer decisions."><Cards items={[{title:"Live Community Intelligence SaaS",description:"Analyse conversations and discover market opportunities.",href:site.appUrl},{title:"Original research",description:"Research and case studies explaining what communities mean.",href:"/research"},{title:"Community Intelligence Scorecard",description:"Measure trust, consensus and authority beyond mentions.",href:"https://blog.theredditrepreneur.com/the-redditrepreneur-community-intelligence-scorecard/"},{title:"Community Intelligence Weekly",description:"The conversations and developments worth watching.",href:"https://theredditrepreneur.substack.com/"},{title:"Community Intelligence Index",description:"A recurring view of the signals shaping brands and markets.",href:"/research"},{title:"Product Hunt launch",description:"Explore The Redditrepreneur’s platform launch.",href:"https://www.producthunt.com/products/the-redditrepreneur/launches/the-redditrepreneur"}]}/></Section>
 <Section eyebrow="Define the category" title="What Is Community Intelligence?" intro="Community Intelligence is the practice of analysing conversations across online communities to understand customer behaviour, competitor positioning, emerging trends and market opportunities." className="alt"><div className="split"><div className="prose"><p>Social listening tells you what was mentioned. Community Intelligence helps you understand what people believe, recommend and decide.</p><div className="button-row"><Link className="button" href="/community-intelligence">Explore Community Intelligence</Link><a className="button secondary" href="https://blog.theredditrepreneur.com/glossary/">Explore the glossary</a></div></div><div className="card"><h3>From signal to decision</h3><p>Understand context, trust, recommendations, behaviour, consensus, competitor positioning, recurring pain points and emerging opportunities.</p></div></div></Section>
 <Section eyebrow="Platform" title="Turn Conversations Into Actionable Intelligence" intro="Use the platform to understand selected conversations, discover relevant signals and build decision-ready intelligence."><Cards items={[{title:"Analyse",description:"Paste selected conversations and turn them into structured themes, opportunities, business impact and recommended actions.",href:"/platform/analyse"},{title:"Discover",description:"Enter a brand, market or competitor and discover relevant public conversations and strategic opportunities.",href:"/platform/discover"},{title:"Alerts",description:"Continuous monitoring is in development. Explore the planned capability and current availability.",href:"/platform/alerts",label:"Coming soon"}]}/><div className="button-row"><a className="button" href={site.appUrl}>Explore the Platform</a></div></Section>
 <Section eyebrow="The Scorecard" title="Measure More Than Mentions" intro="The Community Intelligence Scorecard measures how a brand performs across the conversations that shape trust, recommendations and buying decisions." className="dark"><div className="dimensions">{["Community Presence","Community Trust","Share of Consensus","Insight Responsiveness","Community Authority"].map((x,i)=><div className="dimension" key={x}><span>0{i+1}</span><strong>{x}</strong></div>)}</div><div className="button-row"><a className="button" href="https://blog.theredditrepreneur.com/the-redditrepreneur-community-intelligence-scorecard/">Explore the Scorecard</a><a className="button secondary" href="https://blog.theredditrepreneur.com/the-redditrepreneur-community-intelligence-scorecard-gymshark/">Read the Gymshark Scorecard</a></div></Section>
 <Section eyebrow="Original research" title="Research That Explains What Communities Mean" intro="Curated work from The Redditrepreneur’s canonical research and publication properties."><Cards items={research}/><div className="button-row"><a className="button" href={site.blogUrl}>Explore All Research</a></div></Section>
 <Section eyebrow="Frameworks" title="A Growing Language for Community Intelligence" intro="Approved concepts for interpreting how communities form beliefs, create consensus and influence markets." className="alt"><Cards items={frameworks}/><div className="button-row"><a className="button" href={site.researchUrl}>Explore the Knowledge Base</a></div></Section>
 <Section eyebrow="Solutions" title="Community Intelligence for Better Decisions"><Cards items={solutions.map(x=>({...x,href:`/solutions/${x.slug}`}))}/></Section>
 <Section eyebrow="Who it is for" title="Built for Teams That Need to Understand Their Market" className="alt"><Cards items={["Founders","Marketing teams","Product teams","Insight teams","Community teams","Agencies"].map(title=>({title,description:"Make decisions with the context, language and signals found in real community conversations.",href:"/solutions"}))}/></Section>
 <Section eyebrow="Professional services" title="Expert Community Intelligence, When You Need It" intro="Human-led research and strategy for teams that need deeper investigation, clear recommendations and practical capability."><Cards items={services.slice(0,4).map(x=>({title:x.title,description:`${x.description}${"price" in x&&x.price?` ${x.price}.`:""}`,href:`/services/${x.slug}`}))}/><div className="button-row"><Link className="button" href="/services">Explore Services</Link></div></Section>
 <Section eyebrow="Digital products" title="Build Authority With The Redditrepreneur Systems" className="alt"><div className="product-grid">{products.map(p=><ProductCard key={p.slug} product={p}/>)}</div></Section>
 <Section eyebrow="Community Intelligence Weekly" title="Stay Ahead of the Conversations Shaping Brands, Markets and Culture"><div className="split"><div><p className="lede">Original research, industry developments, Community Intelligence insights and the conversations worth watching.</p><div className="button-row"><a className="button" href="https://theredditrepreneur.substack.com/">Subscribe on Substack</a><a className="button secondary" href="https://theredditrepreneur.substack.com/archive">Browse the archive</a></div></div><div className="media"><Image src="/newsletter/community-intelligence-weekly.png" alt="The Redditrepreneur Community Intelligence Weekly newsletter" width={1778} height={887}/></div></div></Section>
 <Section eyebrow="About the founder" title="Built by Tonte Bo Douglas" className="alt"><div className="split"><Image className="founder" src="/founder/tonte-bo-douglas.jpg" alt="Tonte Bo Douglas, founder of The Redditrepreneur" width={400} height={400}/><div className="prose"><p>The Redditrepreneur began as a way for Tonte Bo Douglas to package his Reddit expertise into a consultancy. It evolved into a Community Intelligence company combining software, services, original research, frameworks and educational products.</p><p>Tonte’s work focuses on understanding what online communities reveal about brands, markets and customer behaviour.</p><div className="button-row"><Link className="button" href="/about">Read Our Story</Link><a className="button secondary" href="https://www.linkedin.com/in/tontebodouglas">Connect on LinkedIn</a></div></div></div></Section>
 <Section eyebrow="Start with the platform" title="See What Your Communities Are Telling You" intro="Explore the Community Intelligence platform and turn online conversations into clearer business decisions." className="dark"><div className="button-row"><a className="button" href={primaryCta.href}>{primaryCta.label}</a><a className="button secondary" href={site.blogUrl}>Read the Research</a></div></Section>
 </>}
