import Image from "next/image";
import Link from "next/link";
import { EcosystemGrid, ResearchGrid } from "@/components/HomeSections";
import { Cards, ProductCard, Section } from "@/components/Sections";
import { audiences, frameworks, scorecardDimensions } from "@/lib/home-content";
import { primaryCta, products, services, site, solutions } from "@/lib/site";

export default function Home(){return <>
  <section className="hero"><div className="shell hero-grid"><div className="hero-copy"><p className="eyebrow">The Home of Community Intelligence</p><h1>Understand What Online Communities Really Think.</h1><p className="lede">Turn real conversations into customer insight, competitor intelligence and better business decisions.</p><div className="button-row"><a className="button" href={site.appUrl}>Explore the Community Intelligence Platform</a><Link className="button secondary" href="/community-intelligence">What Is Community Intelligence?</Link></div><div className="hero-definition"><p><strong>Community Intelligence</strong> is the practice of analysing conversations across online communities to understand customer behaviour, competitor positioning, emerging trends and market opportunities.</p><p>Social listening tells you what was mentioned. Community Intelligence helps you understand what people believe, recommend and decide.</p></div></div><div className="hero-visual"><Image src="/platform/dashboard.jpg" alt="The Redditrepreneur dashboard for analysing conversations and discovering community opportunities" width={1920} height={1080} priority sizes="(max-width: 980px) 100vw, 56vw"/></div></div></section>

  <Section eyebrow="One connected company" title="Community Intelligence, Built Into a Complete Ecosystem" intro="Research creates the evidence. Frameworks organise the thinking. Scorecards make performance visible. Software and expert services turn insight into action."><EcosystemGrid/></Section>

  <Section eyebrow="Platform" title="Turn Conversations Into Actionable Intelligence" intro="Choose the capability that matches the decision you need to make." className="alt"><Cards items={[{title:"Analyse",description:"Understand what selected conversations mean and turn them into structured findings and recommended actions.",href:"/platform/analyse",label:"See how Analyse works"},{title:"Discover",description:"Find the public conversations shaping your brand, market and competitors.",href:"/platform/discover",label:"See how Discover works"},{title:"Alerts",description:"Know when sentiment, competitor activity or high intent conversations begin to change.",href:"/platform/alerts",label:"Coming soon"}]}/><div className="button-row"><a className="button" href={site.appUrl}>Explore the Platform</a></div></Section>

  <Section eyebrow="The Scorecard" title="Measure More Than Mentions" intro="The Community Intelligence Scorecard measures how a brand performs across the conversations that shape trust, recommendations and buying decisions." className="dark"><div className="dimensions">{scorecardDimensions.map((item,i)=><div className="dimension" key={item.title}><span>0{i+1}</span><strong>{item.title}</strong><p>{item.description}</p></div>)}</div><div className="notice" style={{marginTop:24,color:"var(--ink)"}}><strong>Editorial research example:</strong> The Gymshark analysis shows how the five dimensions can be applied to published community research. It is not an automated customer score.</div><div className="button-row"><a className="button" href="https://blog.theredditrepreneur.com/the-redditrepreneur-community-intelligence-scorecard/">View the Scorecard Methodology</a><a className="button secondary" href="https://blog.theredditrepreneur.com/the-redditrepreneur-community-intelligence-scorecard-gymshark/">Read the Gymshark Scorecard</a></div></Section>

  <Section eyebrow="Original research" title="Research That Explains What Communities Mean" intro="Six canonical reports and case studies from The Redditrepreneur publication."><ResearchGrid/><div className="button-row"><a className="button" href={site.blogUrl}>Read All Research</a></div></Section>

  <Section eyebrow="Frameworks" title="A Growing Language for Community Intelligence" intro="Approved concepts for interpreting how communities form beliefs, create consensus and influence markets." className="alt"><Cards items={frameworks}/><div className="button-row"><a className="button" href="https://research.theredditrepreneur.com">Browse the Frameworks</a></div></Section>

  <Section eyebrow="Solutions" title="Community Intelligence for Better Decisions"><Cards items={solutions.map(x=>({...x,href:`/solutions/${x.slug}`,label:`Community Intelligence for ${x.title}`}))}/></Section>

  <Section eyebrow="Who it is for" title="Built for Teams That Need to Understand Their Market" className="alt"><Cards items={audiences.map(item=>({...item,label:`For ${item.title}`}))}/></Section>

  <Section eyebrow="Professional services" title="Expert Community Intelligence, When You Need It"><div className="audit-feature"><Image src="/services/community-intelligence-audit.png" alt="Community Intelligence Audit service cover" width={800} height={800}/><div><p className="eyebrow">Primary service · £595 · Delivered within seven days</p><h3>Community Intelligence Audit</h3><p className="lede">A strategic analysis led by a human expert, covering the conversations shaping your brand, competitors and market.</p><ul className="audit-points"><li>Executive summary</li><li>Opportunity map</li><li>Competitor intelligence</li><li>Community sentiment</li><li>Business impact</li><li>Recommended actions</li></ul><p>Built for teams preparing a major positioning, product, marketing or competitive decision.</p><div className="button-row"><Link className="button" href="/services/community-intelligence-audit">Learn About the Audit</Link></div></div></div><Cards items={services.slice(1,4).map(x=>({title:x.title,description:x.description,href:`/services/${x.slug}`,label:x.slug==="competitor-intelligence-analysis"?"Request Competitor Analysis":"Make an Enquiry"}))}/><div className="button-row"><Link className="button secondary" href="/services">View All Services</Link></div></Section>

  <Section eyebrow="Digital products" title="Build Authority With The Redditrepreneur Systems" className="alt"><div className="product-grid">{products.map(p=><ProductCard key={p.slug} product={p}/>)}</div></Section>

  <Section eyebrow="Community Intelligence Weekly" title="Stay Ahead of the Conversations Shaping Brands, Markets and Culture"><div className="split newsletter-feature"><div><p className="eyebrow">Latest edition</p><h3>Reddit's New Community Intelligence Tools, Gen Z's Search Shift and the Rise of Community Commerce</h3><p className="lede">Each week, receive original research, industry developments, practical Community Intelligence insight and the conversations worth watching.</p><div className="button-row"><a className="button" href="https://theredditrepreneur.substack.com/">Subscribe to Weekly</a><a className="button secondary" href="https://theredditrepreneur.substack.com/archive">Browse the Archive</a></div></div><div className="media"><Image src="/newsletter/community-intelligence-weekly.png" alt="The Redditrepreneur Community Intelligence Weekly newsletter cover" width={1778} height={887}/></div></div></Section>

  <Section eyebrow="About the founder" title="Built by Tonte Bo Douglas" className="alt"><div className="split"><Image className="founder" src="/founder/tonte-bo-douglas.jpg" alt="Tonte Bo Douglas, founder of The Redditrepreneur" width={400} height={400}/><div className="prose"><p>The Redditrepreneur began as Tonte Bo Douglas's Reddit consultancy. It evolved into a Community Intelligence company combining software, original research, strategic frameworks and expert services.</p><p>Tonte's work focuses on what online communities reveal about brands, markets and customer behaviour, then turning that evidence into clearer action.</p><div className="button-row"><Link className="button" href="/about">Read Our Story</Link><a className="button secondary" href="https://www.linkedin.com/in/tontebodouglas">Connect on LinkedIn</a></div></div></div></Section>

  <Section eyebrow="Start with the platform" title="See What Your Communities Are Telling You" intro="Turn online conversations into clearer business decisions." className="dark"><div className="button-row"><a className="button" href={primaryCta.href}>{primaryCta.label}</a><a className="button secondary" href={site.blogUrl}>Read the Research</a></div></Section>
</>}
