import Image from "next/image";
import Link from "next/link";
import { ResearchGrid } from "@/components/HomeSections";
import { PublicationCard } from "@/components/PublicationCard";
import { Section } from "@/components/Sections";
import { BrandEngagementCard, BrandEngagementSectionView, EngagementCta } from "@/components/BrandEngagement";
import { featuredBrandEngagements } from "@/lib/brand-engagements";
import { commercialOffers, communityIntelligenceBenefits, industries, researchCategories } from "@/lib/home-content";
import { services, site } from "@/lib/site";
import { featuredPublications } from "@/lib/publications";

export default function Home(){
  const serviceOffers=commercialOffers.map(offer=>({offer,service:services.find(item=>item.slug===offer.slug)})).filter(item=>item.service);
  return <>
    <section className="hero publication-hero"><div className="shell"><div className="publication-hero-copy"><p className="eyebrow">The Redditrepreneur Research</p><h1>We publish Community Intelligence for the world&apos;s most important industries.</h1><p className="lede">Helping businesses understand what online communities really think, what they trust, what they reject and what businesses should do next.</p><div className="button-row"><a className="button" href={site.blogUrl}>Explore the research</a><a className="button secondary" href="#services">Work with us</a></div></div><div className="publication-strip" aria-label="Research coverage"><span>Gaming</span><span>AI</span><span>Sport</span><span>SaaS</span><span>Consumer Brands</span><span>Entertainment</span></div></div></section>

    <Section id="industries" eyebrow="Our coverage" title="Industries we track" intro="We study how communities shape reputation, trust, buying decisions and culture across the world’s most important industries."><div className="industry-grid">{industries.map(item=><article className="industry-card" key={item.title}><span className="industry-icon" aria-hidden>{item.icon}</span><h3>{item.title}</h3><p>{item.description}</p><a className="text-link" href={item.href}>{item.label} <span aria-hidden>→</span></a></article>)}</div></Section>

    <Section eyebrow="New from the publication" title="Latest research" intro="The latest Community Intelligence analysis from The Redditrepreneur." className="alt"><ResearchGrid/><div className="button-row"><a className="button" href={site.blogUrl}>View all research</a></div></Section>

    <Section id="publications" eyebrow="Our publishing ecosystem" title="Our Publications" intro="The Redditrepreneur creates specialist publications that help people understand important online communities and emerging industries. Our publications combine clear editorial analysis, practical guidance and original research."><div className="publication-list">{featuredPublications.map(publication=><PublicationCard key={publication.name} publication={publication} secondaryHref="/publications#community-intelligence-in-practice"/>)}</div><div className="button-row"><Link className="button secondary" href="/publications">Explore all publications</Link></div></Section>

    <Section eyebrow="What we publish" title="Research built from real community conversations"><div className="publication-intro"><div className="prose"><p>Most businesses rely on surveys, reviews and internal dashboards.</p><p>The Redditrepreneur studies the conversations people have when brands are not in the room.</p><p>We turn those conversations into clear research on trust, reputation, customer needs, market shifts and emerging risks.</p></div><div className="research-category-grid">{researchCategories.map(item=><article key={item.title}><span aria-hidden>{item.icon}</span><div><h3>{item.title}</h3><p>{item.description}</p></div></article>)}</div></div></Section>

    <Section eyebrow="The methodology" title="What is Community Intelligence?" intro="Community Intelligence is the process of turning online conversations into useful business insight." className="ci-explainer dark"><div className="ci-benefit-grid">{communityIntelligenceBenefits.map(item=><div key={item}><span aria-hidden>✓</span><strong>{item}</strong></div>)}</div><div className="button-row"><a className="button" href="https://blog.theredditrepreneur.com/frameworks">Explore our frameworks</a><Link className="button secondary" href="/community-intelligence">Learn about Community Intelligence</Link></div></Section>

    <Section eyebrow="Community Intelligence in practice" title="Brands are joining the conversation" intro="Public responses to The Redditrepreneur’s Scorecards and research show how Community Intelligence can create useful conversations between organisations and the communities shaping their reputation." className="brand-engagement-home alt"><BrandEngagementSectionView/><div className="brand-engagement-list">{featuredBrandEngagements.map(item=><BrandEngagementCard key={item.slug} item={item} compact/>)}</div><div className="button-row"><EngagementCta className="button" href="https://blog.theredditrepreneur.com/scorecards" eventName="scorecard_cta_clicked">View the Scorecards</EngagementCta><EngagementCta className="button secondary" href="/brands-engaging-with-community-intelligence" eventName="brand_engagement_item_clicked">View brand engagement</EngagementCta></div></Section>

    <Section id="services" eyebrow="Work with The Redditrepreneur" title="Apply Community Intelligence to your business" intro="Our research shows what is happening across industries. Our audits, workshops and software help businesses understand what is happening around their own brand."><div className="commercial-grid">{serviceOffers.map(({offer,service})=>service&&<article className="commercial-card" key={offer.slug}><p className="commercial-type">{offer.title||service.title}</p>{"price" in service&&service.price&&<p className="price">{service.price}</p>}<p><strong>What it is:</strong> {service.description}</p><p><strong>Who it is for:</strong> {offer.audience}</p><p><strong>What you receive:</strong> {offer.receives}</p><Link className="text-link" href={`/services/${offer.slug}`}>View the service <span aria-hidden>→</span></Link></article>)}<article className="commercial-card software-offer"><p className="commercial-type">Community Intelligence Software</p><p className="price">Subscription plans</p><p><strong>What it is:</strong> Software for analysing conversations, discovering signals and creating clear business insight.</p><p><strong>Who it is for:</strong> Teams that need repeatable Community Intelligence workflows.</p><p><strong>What you receive:</strong> Access to Analyse, Discover and the currently available platform capabilities.</p><Link className="text-link" href="/platform">Explore the software <span aria-hidden>→</span></Link></article></div><div className="button-row"><Link className="button secondary" href="/services">View all services</Link></div></Section>

    <Section eyebrow="Community Intelligence software" title="Turn online discussion into clear business insight" intro="Analyse conversations, discover community signals and turn online discussion into clear business insight." className="software-section alt"><div className="split"><div><div className="software-links"><Link href="/platform/analyse">Analyse</Link><Link href="/platform/discover">Discover</Link><Link href="/platform/alerts">Alerts</Link><a href={`${site.appUrl}/pricing`}>Pricing</a><a href={`${site.appUrl}/sign-in`}>Sign in</a></div><div className="button-row"><a className="button" href={site.appUrl}>Explore the software</a></div></div><div className="media"><Image src="/platform/dashboard.jpg" alt="The Redditrepreneur Community Intelligence software dashboard" width={1920} height={1080} sizes="(max-width: 980px) 100vw, 50vw"/></div></div></Section>

    <Section eyebrow="Community Intelligence Weekly" title="Follow the conversations shaping brands, markets and culture"><div className="split newsletter-feature"><div><p className="lede">Receive original research, industry developments and practical Community Intelligence insight each week.</p><div className="button-row"><a className="button" href="https://theredditrepreneur.substack.com/">Subscribe to Weekly</a><a className="button secondary" href="https://theredditrepreneur.substack.com/archive">Browse the archive</a></div></div><div className="media"><Image src="/newsletter/community-intelligence-weekly.png" alt="The Redditrepreneur Community Intelligence Weekly publication cover" width={1778} height={887}/></div></div></Section>

    <Section eyebrow="About The Redditrepreneur" title="A Community Intelligence publication and research company" className="alt"><div className="split"><Image className="founder" src="/founder/tonte-bo-douglas.jpg" alt="Tonte Bo Douglas, founder of The Redditrepreneur" width={400} height={400}/><div className="prose"><p>The Redditrepreneur is a Community Intelligence publication and research company founded by Tonte Bo Douglas.</p><p>We study what online communities say about brands, industries, products and culture. Our research helps businesses understand trust, reputation, customer behaviour, emerging risks and market opportunities.</p><p>We publish editorial analysis, original frameworks, Scorecards, indexes and industry research. Businesses can also apply our methodology through audits, workshops, advisory work and software.</p><div className="button-row"><Link className="button" href="/about">About The Redditrepreneur</Link><Link className="button secondary" href="/contact">Contact us</Link></div></div></div></Section>

    <Section eyebrow="Start with the research" title="Understand the conversation before it shapes your business" intro="Read the latest Community Intelligence or apply the methodology to your organisation." className="dark"><div className="button-row"><a className="button" href={site.blogUrl}>Explore the research</a><a className="button secondary" href="#services">Work with us</a></div></Section>
  </>;
}
