import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { FractionalPageView, TrackedLink } from "@/components/TrackedLink";
import { Section } from "@/components/Sections";
import { fractionalCci as service } from "@/lib/fractional-cci";
import { site } from "@/lib/site";

const canonical = `${site.url}/services/${service.slug}`;

export const metadata: Metadata = {
  title: service.seo.title,
  description: service.seo.description,
  alternates: { canonical },
  openGraph: { title: `${service.serviceTitle} | ${site.name}`, description: service.seo.description, url: canonical, type: "website", images: [{ url: service.coverImage, width: 1526, height: 1017, alt: `${service.serviceTitle}: ${service.headline}` }] },
  twitter: { card: "summary_large_image", title: `${service.serviceTitle} | ${site.name}`, description: service.seo.description, images: [service.coverImage] },
};

const problems = ["Customer insight lives across disconnected tools and teams.","Competitor narratives change without executive visibility.","Community feedback does not reach product or leadership decisions.","AI search authority is treated separately from customer belief.","Teams measure mentions without understanding consensus.","Recurring community risks are identified too late."];
const role = ["Interprets community conversations","Advises founders and leadership teams","Connects insight across marketing, product, brand and customer research","Tracks changing narratives and recommendation behaviour","Identifies strategic risks and opportunities","Improves AI Authority","Turns research into clear, prioritised actions"];
const cadence = [["Week 1","Community and market research"],["Week 2","Analysis, Scorecard updates and executive briefing preparation"],["Week 3","Leadership strategy session"],["Week 4","Strategic follow up, messaging or product review and next priority setting"]] as const;
const audiences = [["Founders and CEOs","Gain an external strategic perspective on the conversations influencing your market."],["Marketing leaders","Connect customer language, recommendations and objections to positioning and campaigns."],["Product leaders","Turn recurring community pain points and unmet needs into clearer product priorities."],["Insight teams","Add unsolicited community evidence to surveys, analytics and traditional customer research."],["Brand leaders","Understand the narratives strengthening or weakening trust and recommendation behaviour."],["B2B SaaS and consumer brands","Track market beliefs, competitor movements and the conversations influencing buying decisions."],["Agencies","Strengthen major client research and strategy with structured community evidence."],["Businesses navigating change","Bring leadership clarity to AI search, reputation or fast moving competitive shifts."]] as const;
const excluded = ["Daily social posting","Community moderation","Customer support","Reddit account management","Paid media management","General copywriting","Unlimited content production","Full product implementation","24 hour operational support"];
const deliverables = ["Monthly Executive Community Intelligence Briefing","Community Intelligence Scorecard updates","Competitor narrative tracking","AI Authority recommendations","Risk and opportunity alerts","Monthly leadership session","Quarterly strategic roadmap","Product and messaging reviews","Prioritised recommended actions","Direct strategic access"];

export default function FractionalCciPage(){
  const schema = [{"@context":"https://schema.org","@type":"Service",name:service.serviceTitle,serviceType:"Fractional Community Intelligence executive advisory",provider:{"@type":"Organization",name:site.name,url:site.url},url:canonical,description:service.seo.description,areaServed:"Remote",offers:{"@type":"Offer",priceCurrency:"GBP",price:"5000",description:"Engagements start from £5,000 per month and are scoped following application."}},{"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:site.url},{"@type":"ListItem",position:2,name:"Services",item:`${site.url}/services`},{"@type":"ListItem",position:3,name:service.serviceTitle,item:canonical}]},{"@context":"https://schema.org","@type":"FAQPage",mainEntity:service.faqs.map(([name,text])=>({"@type":"Question",name,acceptedAnswer:{"@type":"Answer",text}}))}];
  return <>
    <FractionalPageView/>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
    <header className="page-hero fractional-hero"><div className="shell fractional-hero-grid"><div><p className="eyebrow">{service.serviceTitle}</p><h1>{service.headline}</h1><p className="fractional-lead">Turn online community conversations into executive insight, competitive advantage and better strategic decisions.</p><p className="lede">Most companies have marketing, product and customer insight teams. Very few have one senior leader responsible for understanding what online communities believe, recommend and decide.</p><p>The Redditrepreneur provides that capability without the cost or commitment of a full time executive hire.</p><div className="fractional-price"><strong>{service.price}</strong><span>{service.engagementType} · {service.status} · {service.commitment}</span></div><div className="button-row"><TrackedLink className="button" href={service.applicationUrl} eventName="fractional_cci_apply_clicked">Apply to Work Together</TrackedLink><TrackedLink className="button secondary" href={service.bookingUrl} eventName="fractional_cci_booking_clicked">Request a Discovery Call</TrackedLink></div></div><div className="fractional-cover"><Image src={service.coverImage} alt="Your External Head of Community Intelligence, a remote application only advisory engagement from £5,000 per month" width={1526} height={1017} priority/></div></div></header>

    <Section eyebrow="The leadership gap" title="Most Companies Are Listening. Few Are Interpreting." intro="Analytics, social listening and customer research can produce more information than leadership teams can connect. The missing capability is senior interpretation: one person responsible for turning community evidence into coordinated decisions."><div className="fractional-problem-grid">{problems.map((item,index)=><article key={item}><span>{String(index+1).padStart(2,"0")}</span><p>{item}</p></article>)}</div></Section>

    <Section eyebrow="Embedded strategic leadership" title="What Your External Head of Community Intelligence Does" className="alt"><div className="split"><div><p className="lede">Your external Head of Community Intelligence becomes an embedded strategic partner to the people making consequential brand, product and market decisions.</p><p>{service.description}</p></div><ul className="fractional-checklist">{role.map(item=><li key={item}>{item}</li>)}</ul></div></Section>

    <Section eyebrow="Scope" title="What the Engagement Includes" intro="The engagement combines recurring intelligence, executive interpretation and focused strategic support. It does not promise unlimited execution."><div className="fractional-service-grid">{service.included.map(([title,description])=><article key={title}><h3>{title}</h3><p>{description}</p></article>)}</div></Section>

    <Section eyebrow="A repeatable rhythm" title="How the Partnership Works" className="dark"><div className="fractional-cadence">{cadence.map(([week,activity])=><article key={week}><span>{week}</span><p>{activity}</p></article>)}</div><p className="fractional-cadence-note">The exact cadence is adapted to the organisation, current priorities and agreed engagement scope.</p></Section>

    <Section eyebrow="Designed for leadership" title="Who This Is For"><div className="fractional-audience-grid">{audiences.map(([title,description])=><article key={title}><h3>{title}</h3><p>{description}</p></article>)}</div></Section>

    <Section eyebrow="Clear boundaries" title="This Is Strategic Leadership, Not Community Management" className="alt"><p className="lede">The engagement focuses on interpretation, executive advice and strategic direction. It does not primarily include:</p><ul className="fractional-exclusions">{excluded.map(item=><li key={item}>{item}</li>)}</ul><p>Execution support may be scoped separately where appropriate, with clear deliverables, ownership and limits.</p></Section>

    <Section eyebrow="Tangible outputs" title="What You Will Receive"><ol className="fractional-deliverables">{deliverables.map((item,index)=><li key={item}><span>{String(index+1).padStart(2,"0")}</span>{item}</li>)}</ol></Section>

    <Section eyebrow="The Community Intelligence advantage" title="A Community Intelligence Capability, Not Just Another Consultant" className="alt"><div className="split"><div><p className="lede">The engagement is supported by a connected Community Intelligence capability spanning software, research, Scorecards, frameworks and human led audits.</p><p>This gives leadership a structured way to understand what communities believe, how consensus is changing and what the evidence means for strategy.</p></div><div className="fractional-links"><a href={site.appUrl}>The Redditrepreneur Community Intelligence platform</a><a href={site.blogUrl}>Original Community Intelligence research</a><a href="https://blog.theredditrepreneur.com/the-redditrepreneur-community-intelligence-scorecard/">Community Intelligence Scorecards</a><a href={site.researchUrl}>Proprietary frameworks and research library</a><TrackedLink href="/services/ai-authority-audit" eventName="fractional_cci_related_service_clicked">AI Authority Audit</TrackedLink><TrackedLink href="/services/community-intelligence-audit" eventName="fractional_cci_related_service_clicked">Community Intelligence Audit</TrackedLink></div></div></Section>

    <Section eyebrow="Senior strategic lead" title="Led by Tonte Bo Douglas"><div className="split fractional-founder"><Image src={service.founderImage} alt="Tonte Bo Douglas, founder of The Redditrepreneur and strategic lead for the Fractional Chief Community Intelligence Officer engagement" width={500} height={500}/><div><p className="lede">Tonte Bo Douglas is the founder of The Redditrepreneur and the senior strategic lead for this engagement.</p><p>He has developed The Redditrepreneur's Community Intelligence software, original research, Scorecards, frameworks and methodology. The fractional engagement brings those connected capabilities directly into leadership decision making.</p><div className="button-row"><a className="button secondary" href="https://www.linkedin.com/in/tontebodouglas">Connect on LinkedIn</a></div></div></div></Section>

    <Section eyebrow="Investment" title={service.price} className="fractional-investment dark"><div className="split"><div><p className="lede">Every engagement is scoped around the size of the company, number of markets, research requirements, meeting cadence and level of executive access required.</p><ul><li>{service.commitment}</li><li>{service.engagementType} engagement</li><li>{service.status}</li><li>Limited client capacity based on the research and access required</li></ul></div><div><div className="button-row"><TrackedLink className="button" href={service.applicationUrl} eventName="fractional_cci_apply_clicked">Apply to Work Together</TrackedLink><TrackedLink className="button secondary" href={service.bookingUrl} eventName="fractional_cci_booking_clicked">Request a Discovery Call</TrackedLink></div></div></div></Section>

    <Section eyebrow="Application only" title="How to Apply"><ol className="fractional-process">{["Complete the application","Initial fit review","Discovery call","Engagement scope and proposal","Onboarding and baseline assessment"].map((step,index)=><li key={step}><span>{index+1}</span><strong>{step}</strong></li>)}</ol><p>Submitting an application does not guarantee acceptance. Applications are reviewed for fit, scope and the capacity required to serve the engagement properly.</p><div className="button-row"><TrackedLink className="button" href={service.applicationUrl} eventName="fractional_cci_application_started">Start Your Application</TrackedLink></div></Section>

    <Section eyebrow="Common questions" title="Fractional CCI Officer FAQs" className="alt"><div className="authority-faqs fractional-faqs">{service.faqs.map(([question,answer])=><details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></Section>

    <section className="fractional-final"><div className="shell"><p className="eyebrow">Executive Community Intelligence</p><h2>Give Community Intelligence a Seat at the Leadership Table</h2><p>Bring an external Head of Community Intelligence into your business and turn online conversations into clearer strategic decisions.</p><div className="button-row"><TrackedLink className="button" href={service.applicationUrl} eventName="fractional_cci_apply_clicked">Apply to Work Together</TrackedLink><TrackedLink className="button secondary" href={service.bookingUrl} eventName="fractional_cci_booking_clicked">Request a Discovery Call</TrackedLink></div></div></section>
  </>;
}
