export const fractionalCci = {
  slug: "fractional-chief-community-intelligence-officer",
  serviceTitle: "Fractional Chief Community Intelligence Officer",
  navigationLabel: "Fractional CCI Officer",
  headline: "Your External Head of Community Intelligence",
  description: "The Redditrepreneur acts as your external Head of Community Intelligence, helping your leadership team understand what online communities believe about your brand, competitors and market, then translating those conversations into strategic action.",
  shortDescription: "Ongoing executive advisory that turns online community conversations into strategic insight across brand, product, competitors and AI Authority.",
  price: "From £5,000 per month",
  engagementType: "Remote",
  status: "Application only",
  commitment: "Three month recommended minimum",
  applicationUrl: "https://form.typeform.com/to/xy4Z0oi4",
  bookingUrl: "https://calendly.com/theredditrepreneur/strategy-session",
  supportEmail: "theredditrepreneur@gmail.com",
  founderImage: "/founder/tonte-bo-douglas.jpg",
  coverImage: "/services/fractional-chief-community-intelligence-officer.jpg",
  homepageFeatured: true,
  servicesOrder: 1,
  seo: {
    title: "Fractional Chief Community Intelligence Officer",
    description: "Hire The Redditrepreneur as your external Head of Community Intelligence for executive insight, competitor analysis, AI Authority and strategic advisory from £5,000 per month.",
  },
  included: [
    ["Executive Community Intelligence Briefing", "A monthly executive report covering brand narratives, competitor movements, recommendation behaviour, risks, opportunities and strategic priorities."],
    ["Leadership Strategy Session", "A monthly 90 minute session with founders, executives or senior teams to interpret findings and agree the next actions."],
    ["Community Intelligence Monitoring", "Ongoing analysis of brand, competitor and market conversations, with attention to changing sentiment, consensus and emerging themes."],
    ["Community Intelligence Scorecards", "Regular structured assessment across Community Presence, Community Trust, Share of Consensus, Insight Responsiveness and Community Authority."],
    ["AI Authority Advisory", "Strategic guidance on AI search visibility, citation authority, content gaps, community evidence and answer engine positioning."],
    ["Product and Messaging Reviews", "Review important launches, positioning, campaigns, landing pages and product decisions through a Community Intelligence lens."],
    ["Quarterly Strategic Roadmap", "A prioritised roadmap connecting community evidence to marketing, product, brand and leadership decisions."],
    ["Direct Strategic Access", "Ongoing access through an agreed channel such as email, Slack or Microsoft Teams for strategic questions between scheduled sessions."],
    ["Priority Research", "Focused research into urgent community questions, competitor developments or leadership priorities within the agreed engagement scope."],
  ],
  faqs: [
    ["Is the service fully remote?", "Yes. The engagement is delivered remotely through research, written briefings, scheduled strategy sessions and an agreed communication channel."],
    ["How much does it cost?", "Engagements start from £5,000 per month. Final scope depends on the number of markets, research requirements, meeting cadence and level of executive access required."],
    ["Is there a minimum commitment?", "A three month initial commitment is recommended so there is enough time to establish a baseline, identify patterns and turn findings into strategic action."],
    ["Who will lead the engagement?", "Tonte Bo Douglas, founder of The Redditrepreneur, serves as the senior strategic lead for the engagement."],
    ["How many meetings are included?", "The standard cadence includes one monthly 90 minute leadership strategy session. Any additional meetings are agreed as part of the engagement scope."],
    ["Does this include community management?", "No. This is a strategic leadership engagement, not a daily community management or moderation service."],
    ["Does this include Reddit posting?", "No. Reddit account management and routine posting are not included. Separate execution support may be scoped where appropriate."],
    ["Can you work with an existing marketing or insights team?", "Yes. The role is designed to connect community evidence across leadership, marketing, product, brand and existing customer insight functions."],
    ["What information will you need from us?", "We typically need strategic priorities, key markets, competitor context, existing research and access to the leaders responsible for acting on the findings."],
    ["Can you support multiple brands or markets?", "Yes, where the required scope is practical. Multiple brands or markets may affect the monthly investment and research cadence."],
    ["Is this suitable for agencies?", "Yes. Agencies supporting major clients can use the engagement to strengthen research, positioning and strategic recommendations with community evidence."],
    ["What happens after I apply?", "Applications receive an initial fit review. Suitable applicants are invited to a discovery call before an engagement scope and proposal are prepared. Applying does not guarantee acceptance."],
  ],
} as const;

export const fractionalCciAnalyticsEvents = [
  "fractional_cci_page_viewed",
  "fractional_cci_apply_clicked",
  "fractional_cci_booking_clicked",
  "fractional_cci_application_started",
  "fractional_cci_application_submitted",
  "fractional_cci_related_service_clicked",
] as const;
